version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: snippetbox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["mysqld", "--mysql-native-password=ON"]

volumes:
  mysql_data:
