version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: snippetbox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
