// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Snippet struct {
	ID      int32
	Title   string
	Content string
	Created time.Time
	Expires time.Time
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	Created        time.Time
}
